CREATE DATABASE IF NOT EXISTS virtual_store;
USE virtual_store;
CREATE TABLE IF NOT EXISTS user(
Cedula_Ciudadania INT PRIMARY KEY,
First_Name VARCHAR(50) NOT NULL,
Second_Name VARCHAR(50) NULL,
First_Last_Name VARCHAR(50) NOT NULL,
Second_Last_Name VARCHAR(50) NULL 
);
CREATE TABLE IF NOT EXISTS products(
Id INT AUTO_INCREMENT PRIMARY KEY,
Product_Name VARCHAR(100) NOT NULL,
Brand VARCHAR(100) NOT NULL,
Price DECIMAL(10,2) NULL
);